interface Exercise {
  word: string;
  context: string;
  category: string;
  difficulty: number; // 1-5
  type: "word" | "phrase";
}

export interface Language {
  code: string;
  name: string;
  exercises: Exercise[];
}
export const languagesQuestions: Language[] = [
  {
    code: "en-US",
    name: "English",
    exercises: [
      {
        word: "hello",
        context: "Basic greeting",
        category: "Greetings",
        difficulty: 1,
        type: "word",
      },
      {
        word: "goodbye",
        context: "Parting phrase",
        category: "Greetings",
        difficulty: 1,
        type: "word",
      },
      {
        word: "thank you",
        context: "Express gratitude",
        category: "Politeness",
        difficulty: 1,
        type: "phrase",
      },
      {
        word: "please",
        context: "Polite request",
        category: "Politeness",
        difficulty: 1,
        type: "word",
      },
      {
        word: "restaurant",
        context: "Place to eat",
        category: "Places",
        difficulty: 2,
        type: "word",
      },
      {
        word: "hospital",
        context: "Medical facility",
        category: "Places",
        difficulty: 2,
        type: "word",
      },
      {
        word: "delicious",
        context: "Describing food",
        category: "Food",
        difficulty: 3,
        type: "word",
      },
      {
        word: "How are you?",
        context: "Common greeting",
        category: "Greetings",
        difficulty: 2,
        type: "phrase",
      },
      {
        word: "What's your name?",
        context: "Introduction",
        category: "Social",
        difficulty: 2,
        type: "phrase",
      },
      {
        word: "Where is the bathroom?",
        context: "Asking directions",
        category: "Navigation",
        difficulty: 3,
        type: "phrase",
      },
      {
        word: "I don't understand",
        context: "Communication issue",
        category: "Communication",
        difficulty: 3,
        type: "phrase",
      },
      {
        word: "How much does this cost?",
        context: "Shopping",
        category: "Commerce",
        difficulty: 3,
        type: "phrase",
      },
      {
        word: "Can you help me?",
        context: "Requesting assistance",
        category: "Daily Life",
        difficulty: 3,
        type: "phrase",
      },
      {
        word: "What time is it?",
        context: "Asking for time",
        category: "Daily Life",
        difficulty: 2,
        type: "phrase",
      },
      {
        word: "I would like...",
        context: "Making requests",
        category: "Daily Life",
        difficulty: 3,
        type: "phrase",
      },
      {
        word: "Nice to meet you",
        context: "Introduction",
        category: "Social",
        difficulty: 2,
        type: "phrase",
      },
      {
        word: "Excuse me",
        context: "Getting attention",
        category: "Politeness",
        difficulty: 2,
        type: "phrase",
      },
      {
        word: "I'm sorry",
        context: "Apologizing",
        category: "Politeness",
        difficulty: 2,
        type: "phrase",
      },
      {
        word: "My name is...",
        context: "Introduction",
        category: "Social",
        difficulty: 1,
        type: "phrase",
      },
      {
        word: "Good morning",
        context: "Morning greeting",
        category: "Greetings",
        difficulty: 1,
        type: "phrase",
      },
    ],
  },
  {
    code: "fr-FR",
    name: "French",
    exercises: [
      {
        word: "bonjour",
        context: "Morning greeting",
        category: "Greetings",
        difficulty: 1,
        type: "word",
      },
      {
        word: "au revoir",
        context: "Parting phrase",
        category: "Greetings",
        difficulty: 1,
        type: "phrase",
      },
      {
        word: "merci",
        context: "Express gratitude",
        category: "Politeness",
        difficulty: 1,
        type: "word",
      },
      {
        word: "s'il vous plaît",
        context: "Polite request",
        category: "Politeness",
        difficulty: 1,
        type: "phrase",
      },
      {
        word: "restaurant",
        context: "Place to eat",
        category: "Places",
        difficulty: 2,
        type: "word",
      },
      {
        word: "hôpital",
        context: "Medical facility",
        category: "Places",
        difficulty: 2,
        type: "word",
      },
      {
        word: "délicieux",
        context: "Describing food",
        category: "Food",
        difficulty: 3,
        type: "word",
      },
      {
        word: "Comment ça va?",
        context: "Common greeting",
        category: "Greetings",
        difficulty: 2,
        type: "phrase",
      },
      {
        word: "Comment vous appelez-vous?",
        context: "Introduction",
        category: "Social",
        difficulty: 2,
        type: "phrase",
      },
      {
        word: "Où sont les toilettes?",
        context: "Asking directions",
        category: "Navigation",
        difficulty: 3,
        type: "phrase",
      },
      {
        word: "Je ne comprends pas",
        context: "Communication issue",
        category: "Communication",
        difficulty: 3,
        type: "phrase",
      },
      {
        word: "Combien ça coûte?",
        context: "Shopping",
        category: "Commerce",
        difficulty: 3,
        type: "phrase",
      },
      {
        word: "Pouvez-vous m'aider?",
        context: "Requesting assistance",
        category: "Daily Life",
        difficulty: 3,
        type: "phrase",
      },
      {
        word: "Quelle heure est-il?",
        context: "Asking for time",
        category: "Daily Life",
        difficulty: 2,
        type: "phrase",
      },
      {
        word: "Je voudrais...",
        context: "Making requests",
        category: "Daily Life",
        difficulty: 3,
        type: "phrase",
      },
      {
        word: "Enchanté(e)",
        context: "Introduction",
        category: "Social",
        difficulty: 2,
        type: "word",
      },
      {
        word: "Excusez-moi",
        context: "Getting attention",
        category: "Politeness",
        difficulty: 2,
        type: "phrase",
      },
      {
        word: "Je suis désolé(e)",
        context: "Apologizing",
        category: "Politeness",
        difficulty: 2,
        type: "phrase",
      },
      {
        word: "Je m'appelle...",
        context: "Introduction",
        category: "Social",
        difficulty: 1,
        type: "phrase",
      },
      {
        word: "Bon matin",
        context: "Morning greeting",
        category: "Greetings",
        difficulty: 1,
        type: "phrase",
      },
    ],
  },
  {
    code: "ar-SA",
    name: "Arabic",
    exercises: [
      {
        word: "مرحبا",
        context: "Greeting",
        category: "Greetings",
        difficulty: 1,
        type: "word",
      },
      {
        word: "مع السلامة",
        context: "Parting phrase",
        category: "Greetings",
        difficulty: 1,
        type: "phrase",
      },
      {
        word: "شكرا",
        context: "Express gratitude",
        category: "Politeness",
        difficulty: 1,
        type: "word",
      },
      {
        word: "من فضلك",
        context: "Polite request",
        category: "Politeness",
        difficulty: 1,
        type: "phrase",
      },
      {
        word: "مطعم",
        context: "Place to eat",
        category: "Places",
        difficulty: 2,
        type: "word",
      },
      {
        word: "مستشفى",
        context: "Medical facility",
        category: "Places",
        difficulty: 2,
        type: "word",
      },
      {
        word: "لذيذ",
        context: "Describing food",
        category: "Food",
        difficulty: 3,
        type: "word",
      },
      {
        word: "كيف حالك؟",
        context: "Common greeting",
        category: "Greetings",
        difficulty: 2,
        type: "phrase",
      },
      {
        word: "ما اسمك؟",
        context: "Introduction",
        category: "Social",
        difficulty: 2,
        type: "phrase",
      },
      {
        word: "أين الحمام؟",
        context: "Asking directions",
        category: "Navigation",
        difficulty: 3,
        type: "phrase",
      },
      {
        word: "أنا لا أفهم",
        context: "Communication issue",
        category: "Communication",
        difficulty: 3,
        type: "phrase",
      },
      {
        word: "كم ثمن هذا؟",
        context: "Shopping",
        category: "Commerce",
        difficulty: 3,
        type: "phrase",
      },
      {
        word: "هل يمكنك مساعدتي؟",
        context: "Requesting assistance",
        category: "Daily Life",
        difficulty: 3,
        type: "phrase",
      },
      {
        word: "كم الساعة؟",
        context: "Asking for time",
        category: "Daily Life",
        difficulty: 2,
        type: "phrase",
      },
      {
        word: "أريد...",
        context: "Making requests",
        category: "Daily Life",
        difficulty: 3,
        type: "phrase",
      },
      {
        word: "تشرفنا",
        context: "Introduction",
        category: "Social",
        difficulty: 2,
        type: "word",
      },
      {
        word: "عفوا",
        context: "Getting attention",
        category: "Politeness",
        difficulty: 2,
        type: "word",
      },
      {
        word: "أنا آسف",
        context: "Apologizing",
        category: "Politeness",
        difficulty: 2,
        type: "phrase",
      },
      {
        word: "اسمي...",
        context: "Introduction",
        category: "Social",
        difficulty: 1,
        type: "phrase",
      },
      {
        word: "صباح الخير",
        context: "Morning greeting",
        category: "Greetings",
        difficulty: 1,
        type: "phrase",
      },
    ],
  },
];

export default languagesQuestions;
